// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhYB2i5KwRJ7kzP2llsxHKq8PbAyFqmgI',
    appId: '1:980881966805:web:0cccb4eb87e9ab76ea045c',
    messagingSenderId: '980881966805',
    projectId: 'jsps-297c3',
    authDomain: 'jsps-297c3.firebaseapp.com',
    storageBucket: 'jsps-297c3.firebasestorage.app',
    measurementId: 'G-TDH1Z06G30',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh6WrGr782Xi8EFh4tz8gJ2bKh1W3J6Rg',
    appId: '1:980881966805:android:b29618f624feb050ea045c',
    messagingSenderId: '980881966805',
    projectId: 'jsps-297c3',
    storageBucket: 'jsps-297c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSKS2FttaEgx3FpwPyGfEM_YwY5nMNdMU',
    appId: '1:980881966805:ios:0a47a0e956edc04fea045c',
    messagingSenderId: '980881966805',
    projectId: 'jsps-297c3',
    storageBucket: 'jsps-297c3.firebasestorage.app',
    iosBundleId: 'com.example.jspsPlus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSKS2FttaEgx3FpwPyGfEM_YwY5nMNdMU',
    appId: '1:980881966805:ios:0a47a0e956edc04fea045c',
    messagingSenderId: '980881966805',
    projectId: 'jsps-297c3',
    storageBucket: 'jsps-297c3.firebasestorage.app',
    iosBundleId: 'com.example.jspsPlus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhYB2i5KwRJ7kzP2llsxHKq8PbAyFqmgI',
    appId: '1:980881966805:web:58d5bff81d39304fea045c',
    messagingSenderId: '980881966805',
    projectId: 'jsps-297c3',
    authDomain: 'jsps-297c3.firebaseapp.com',
    storageBucket: 'jsps-297c3.firebasestorage.app',
    measurementId: 'G-VH2QZ8D3M9',
  );
}
